#!/usr/bin/env python3
"""
bakeoff_memo.py
---------------
Purpose : Generate every table in extraction_method_comparison.tex from the scored run, so
          the memo can never quote a number the data no longer supports.
Inputs  : bakeoff/g3_report.json (written by the collector), bakeoff/split.json,
          bakeoff/gold_versions.json, labels.db (adjudication verdicts, provenance).
Outputs : output/planning_commission_project/bakeoff_tables.tex
Author  : Dan Post
Created : 2026-09-06

Notes
-----
Every wide table is wrapped in \\resizebox: the field-level table has one row per schema
field and runs past the margin otherwise (see CLAUDE.md on checking the .log for
"Overfull \\hbox ... in alignment").

Nothing is hand-placed. The cost table is computed from the token counts the API actually
returned for the scored run, not from an estimate of prompt length.
"""
from __future__ import annotations

import json
import sqlite3
import sys
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from extraction_common import SCHEMA, EXTRACTED_FIELDS, SCHEMA_VERSION   # noqa: E402

OUT = HERE / "bakeoff"
DB = HERE / "labeling_app" / "labels.db"
TEX = HERE.parents[1] / "output" / "planning_commission_project" / "bakeoff_tables.tex"
REPORT = OUT / "g3_report.json"

# Haiku 4.5 list price, $/MTok; the Batch API halves all four.
PRICE = {"input": 1.00, "output": 5.00, "cache_read": 0.10, "cache_write": 1.25}
BATCH = 0.5
CORPUS = None            # filled from labels.db

LABEL = {"regex": "Deterministic rules", "haiku-4.5-g3": "Haiku 4.5, few-shot",
         "haiku-4.5-g3cache": "Haiku 4.5, few-shot, cached prefix"}
TEXNAME = lambda f: f.replace("_", r"\_")          # noqa: E731


def esc(s) -> str:
    return str(s).replace("_", r"\_").replace("&", r"\&").replace("%", r"\%")


def corpus_size() -> int:
    con = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
    n = con.execute("""SELECT COUNT(*) FROM items i JOIN labels l ON l.item_id = i.id
                       WHERE i.case_number != '' AND l.status != 'not_an_item'""").fetchone()[0]
    con.close()
    return n


def verdicts() -> tuple:
    con = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
    rows = con.execute("""SELECT field, verdict FROM review_queue
                          WHERE reason='adjudication' AND verdict IS NOT NULL""").fetchall()
    con.close()
    return Counter(v for _, v in rows), defaultdict(Counter,
        {f: Counter(v for g, v in rows if g == f) for f, _ in rows})


def cost_per_item(u: dict) -> float:
    n = u["items"]
    return sum(u[k] / n * PRICE[k] * BATCH / 1e6
               for k in ("input", "output", "cache_read", "cache_write"))


def main():
    rep = json.loads(REPORT.read_text())
    split = json.loads((OUT / "split.json").read_text())
    gv = json.loads((OUT / "gold_versions.json").read_text())[-1]
    n_corpus = corpus_size()
    S, U = rep["scores"], rep["usage"]
    methods = [m for m in ("regex", "haiku-4.5-g3", "haiku-4.5-g3cache") if m in S]
    L = []
    add = L.append

    add("% GENERATED BY bakeoff_memo.py — do not edit by hand.")
    add(r"\begin{table}[htbp]\centering")
    add(r"\caption{Accuracy on the held-out half, by era. Gold version \texttt{%s}, "
        r"%d items (%d train / %d test). Accuracy counts only field-values the gold record "
        r"fills; over-extraction is the separate rate at which a method invents a value the "
        r"gold leaves blank.}" % (esc(gv["version"]), rep["n_gold"],
                                  len(split["train"]), len(split["test"])))
    add(r"\label{tab:headline}")
    add(r"\begin{tabular}{lrrrr}\toprule")
    add(r"Method & Test & Test, HTML & Test, PDF & Over-extraction\\")
    add(r" & \small(n=%d) & \small(n=%d) & \small(n=%d) & \small(n=%d)\\\midrule"
        % (S[methods[0]]["test"]["n_scored"], S[methods[0]]["test_html"]["n_scored"],
           S[methods[0]]["test_pdf"]["n_scored"], S[methods[0]]["test"]["n_blank"]))
    for m in methods:
        s = S[m]
        add(r"%s & %.1f\%% & %.1f\%% & %.1f\%% & %.1f\%%\\"
            % (LABEL.get(m, esc(m)), s["test"]["accuracy"], s["test_html"]["accuracy"],
               s["test_pdf"]["accuracy"], s["test"]["over_extraction"]))
    add(r"\bottomrule\end{tabular}\end{table}")
    add("")

    # ── cost ────────────────────────────────────────────────────────────────
    add(r"\begin{table}[htbp]\centering")
    add(r"\caption{Token cost, measured on the %d-item scored run and extrapolated to the "
        r"%s items in the corpus that carry a case number. Batch API pricing (half of list). "
        r"The two rows differ only in the ORDER of the prompt: putting the constant "
        r"instructions ahead of the per-item examples is what makes a prefix cacheable.}"
        % (rep["n_gold"], f"{n_corpus:,}"))
    add(r"\label{tab:cost}")
    add(r"\resizebox{\textwidth}{!}{%")
    add(r"\begin{tabular}{lrrrrrr}\toprule")
    add(r"Configuration & Input & Cache read & Cache write & Output & \$/1{,}000 items "
        r"& \$/corpus\\")
    add(r"& \multicolumn{4}{c}{\small tokens per item} & & \small(%s items)\\\midrule"
        % f"{n_corpus:,}")
    for m in methods:
        if m not in U:
            continue
        u = U[m]; n = u["items"]
        c = cost_per_item(u)
        add(r"%s & %s & %s & %s & %s & \$%.2f & \$%.2f\\"
            % (LABEL.get(m, esc(m)), f"{u['input']/n:,.0f}", f"{u['cache_read']/n:,.0f}",
               f"{u['cache_write']/n:,.0f}", f"{u['output']/n:,.0f}",
               c * 1000, c * n_corpus))
    add(r"\bottomrule\end{tabular}}\end{table}")
    add("")

    # ── field level ─────────────────────────────────────────────────────────
    best = "haiku-4.5-g3cache" if "haiku-4.5-g3cache" in S else methods[-1]
    bf = S[best].get("by_field_test", {})
    rbf = S["regex"].get("by_field_test", {}) if "regex" in S else {}
    add(r"\begin{table}[htbp]\centering")
    add(r"\caption{Field-level accuracy on the held-out half. Fields the schema marks "
        r"\texttt{derived} are computed in Python and never asked of the model; fields with "
        r"fewer than ten scored values are shown but should not be read as rates.}")
    add(r"\label{tab:byfield}")
    add(r"\resizebox{\textwidth}{!}{%")
    add(r"\begin{tabular}{llrrr}\toprule")
    add(r"Section & Field & $n$ & Rules & %s\\\midrule" % LABEL[best].split(",")[0])
    sec = None
    for f in SCHEMA:
        name = f["name"]
        if name not in EXTRACTED_FIELDS or name not in bf:
            continue
        if f["section"] != sec:
            sec = f["section"]
            add(r"\multicolumn{5}{l}{\itshape %s}\\" % esc(sec))
        r_acc = rbf.get(name, {}).get("acc")
        add(r" & \texttt{%s} & %d & %s & %.1f\%%\\"
            % (TEXNAME(name), bf[name]["n"],
               (r"%.1f\%%" % r_acc) if r_acc is not None else "---", bf[name]["acc"]))
    add(r"\bottomrule\end{tabular}}\end{table}")
    add("")

    # ── adjudication ────────────────────────────────────────────────────────
    tot, byf = verdicts()
    n = sum(tot.values())
    if n:
        add(r"\begin{table}[htbp]\centering")
        add(r"\caption{Adjudicated disagreements. Every case where the model's value differed "
            r"from the hand label was judged against the source block. `Gold' means the label "
            r"stood; `model' means the label was wrong and was corrected. The model column is "
            r"the share of apparent model error that was never model error.}")
        add(r"\label{tab:adjudication}")
        add(r"\begin{tabular}{lrr}\toprule")
        add(r"Verdict & Count & Share\\\midrule")
        for k, lab in (("gold", "The hand label was right"),
                       ("model", "The model was right; gold corrected"),
                       ("both", "Neither was right")):
            add(r"%s & %d & %.1f\%%\\" % (lab, tot[k], 100 * tot[k] / n))
        add(r"\midrule Total adjudicated & %d & \\" % n)
        add(r"\bottomrule\end{tabular}\end{table}")
        add("")

    # ── evidence verification ───────────────────────────────────────────────
    add(r"\begin{table}[htbp]\centering")
    add(r"\caption{Evidence-span verification. On six fields the model must return the words "
        r"in the block that support its value; the span is checked as a verbatim substring "
        r"after whitespace normalisation. A failure is a triage signal, not a correction --- "
        r"the value is flagged, never nulled.}")
    add(r"\label{tab:evidence}")
    add(r"\begin{tabular}{lrr}\toprule")
    add(r"Configuration & Failures & Per 100 items\\\midrule")
    for m in methods:
        if m not in U:
            continue
        u = U[m]
        add(r"%s & %d & %.1f\\" % (LABEL.get(m, esc(m)), u["evidence_failures"],
                                   100 * u["evidence_failures"] / u["items"]))
    add(r"\bottomrule\end{tabular}\end{table}")

    TEX.write_text("\n".join(L) + "\n")
    print(f"→ {TEX}  ({len(L)} lines)")
    print(f"   gold {gv['version']}, {rep['n_gold']} items, corpus {n_corpus:,}")
    for m in methods:
        if m in U:
            print(f"   {m:20s} ${cost_per_item(U[m])*n_corpus:,.2f} for the corpus")


if __name__ == "__main__":
    main()
